name = "hive-avances"
compatibility_date = "2026-05-25"
pages_build_output_dir = "."

[[d1_databases]]
binding = "DB"
database_name = "hive_avances"
database_id = "REEMPLAZAR_CON_DATABASE_ID"

[[r2_buckets]]
binding = "PHOTOS"
bucket_name = "hive-avances-photos"
